package root.cyb.mh.attendancesystem.model.enums;

public enum IssueType {
    PORT_FLAPPING,
    SPEED_NEGOTIATION_MISMATCH,
    PACKET_LOSS_LATENCY,
    CABLE_OR_CONNECTOR_FAULT,
    IP_MAC_CONFLICT,
    VLAN_MISCONFIGURATION,
    DOWNTIME_DISCONNECTED,
    POE_FAILURE,
    HARDWARE_FAULT,
    BANDWIDTH_ABUSE,
    ROGUE_DEVICE_DETECTED,
    OTHER
}
